jobs:
- job: Linux_1
  strategy:
    matrix:
      gcc_6:
        gcc_version: '6'
      gcc_7:
        gcc_version: '7'
      gcc_8:
        gcc_version: '8'
      gcc_9:
        gcc_version: '9'
  pool:
    vmImage: ubuntu-18.04
  variables:
    CC: gcc-$(gcc_version)
    CXX: g++-$(gcc_version)
  timeoutInMinutes: 360
  steps:

  - script: |
      if [[ $(gcc_version) == '4.9' || $(gcc_version) == '6' || $(gcc_version) == '7' || $(gcc_version) == '8' ]]; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get --no-install-suggests --no-install-recommends install g++-$(gcc_version)
      fi
    displayName: Install build toolchain

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - template: unix-build.yml
